services:
  zabbix-server:
    image: zabbix/zabbix-server-pgsql:alpine-7.0-latest
    container_name: zabbix-server
    restart: always
    ports:
      - "10051:10051"
    environment:
      DB_SERVER_HOST: zabbix-db
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix123
      POSTGRES_DB: zabbix_db
      ZBX_ENABLE_SNMP_TRAPS: "true"
    networks:
      - zabbix_net

networks:
  zabbix_net:
    external: true
