services:
  grafana-db:
    image: postgres:17
    container_name: grafana-db
    restart: always
    environment:
      POSTGRES_USER: grafana
      POSTGRES_PASSWORD: grafana123
      POSTGRES_DB: grafana
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - zabbix_net

volumes:
  postgres-data:

networks:
  zabbix_net:
    external: true
